name: Woke
on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master
      - feature/2.0.0

jobs:
  woke:
    name: Run Woke
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: woke
        uses: get-woke/woke-action@v0
        with:
          fail-on-error: true
          github-token: ${{ secrets.GITHUB_TOKEN }}
